import type { Metadata } from 'next';
import { Varela_Round } from 'next/font/google';
import './globals.css';

import { Header } from './components';

const varelaRound = Varela_Round({
  subsets: ['latin'],
  display: 'auto',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/logo-red.svg" type="image/x-icon" />
        <title>Peakfocus</title>
      </head>
      <body className={`${varelaRound.className}  antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
